export {default as Dashboard} from "./dashboard";
export {default as Bar }from "./bar";
export {default as Form }from "./form";
export {default as Line }from "./line";
export {default as Pie }from "./pie";
export {default as FAQ }from "./faq";
export {default as Login }from "./login";
export {default as Geography }from "./geography";
export {default as Calendar }from "./calendar/calendar";
export {default as NotFoundPage }from "./errorPage/NotFoundPage ";
export {default as RootLayout }from "./Root.js";
export {default as ProfilePage }from "./profile/ProfilePage.jsx";
export {default as HospitalPayment }from "./hospitalpayment/HospitalPayment.jsx";
export {default as ReportPage }from "./reports/ReportPage.jsx";
export {default as BankerComponent }from "./supervisors/BankerComponent.jsx";
export {default as CollectedReport }from "./reports/CollectedReport.jsx";